// Realistic mock data for the Afya24 clickable prototype.
// Nothing here is a real API call — components should be structured so a
// future TanStack Query hook can replace these exports without changing shape.

import type {
  AdminProviderMeta,
  AiQualification,
  Appointment,
  AuditLogEntry,
  Checkout,
  Intake,
  LabLocation,
  LabOrder,
  PatientFile,
  Payment,
  PharmacyItem,
  PharmacyOrder,
  Provider,
  Service,
  ServiceCategory,
  VisitOutcome,
} from "./types";

export const serviceCategories: ServiceCategory[] = [
  {
    id: "cat-general",
    name: "General doctor",
    description: "Talk to a general practitioner about any everyday health concern.",
    icon: "stethoscope",
    popularServices: ["svc-general-consult", "svc-followup"],
  },
  {
    id: "cat-urgent",
    name: "Urgent care",
    description: "Same-day care for issues that need attention soon but aren't emergencies.",
    icon: "alarm-clock",
    popularServices: ["svc-urgent-consult"],
  },
  {
    id: "cat-mental-health",
    name: "Mental health",
    description: "Support for anxiety, depression, stress, and sleep issues.",
    icon: "brain",
    popularServices: ["svc-mental-health-consult"],
  },
  {
    id: "cat-dermatology",
    name: "Dermatology",
    description: "Skin, hair, and nail concerns reviewed by a doctor.",
    icon: "scan-face",
    popularServices: ["svc-derm-consult"],
  },
  {
    id: "cat-sexual-health",
    name: "Sexual health",
    description: "Confidential care for sexual and reproductive health concerns.",
    icon: "heart-pulse",
    popularServices: ["svc-sexual-health-consult"],
  },
  {
    id: "cat-prescription",
    name: "Prescription refill",
    description: "Renew an existing prescription without an in-person visit.",
    icon: "pill",
    popularServices: ["svc-refill-consult"],
  },
  {
    id: "cat-lab",
    name: "Lab tests",
    description: "Get a doctor's referral for lab tests at a nearby partner lab.",
    icon: "flask-conical",
    popularServices: ["svc-lab-referral"],
  },
  {
    id: "cat-womens-health",
    name: "Women's health",
    description: "Care for menstrual, reproductive, and general women's health concerns.",
    icon: "heart-pulse",
    popularServices: ["svc-womens-health-consult"],
  },
  {
    id: "cat-pediatrics",
    name: "Pediatrics",
    description: "Care for your child from a doctor experienced in pediatric health.",
    icon: "baby",
    popularServices: ["svc-pediatric-consult"],
  },
  {
    id: "cat-chronic",
    name: "Chronic condition follow-up",
    description: "Ongoing check-ins for diabetes, hypertension, asthma, and similar conditions.",
    icon: "repeat",
    popularServices: ["svc-chronic-followup"],
  },
];

export const services: Service[] = [
  {
    id: "svc-general-consult",
    categoryId: "cat-general",
    name: "General consultation",
    description: "A general check-in for any health concern with a licensed doctor.",
    startingPrice: 10000,
    consultationModes: ["chat", "voice", "video"],
    estimatedDuration: 15,
  },
  {
    id: "svc-followup",
    categoryId: "cat-general",
    name: "Follow-up visit",
    description: "A shorter visit to review progress after a previous consultation.",
    startingPrice: 7000,
    consultationModes: ["chat", "voice", "video"],
    estimatedDuration: 10,
  },
  {
    id: "svc-urgent-consult",
    categoryId: "cat-urgent",
    name: "Urgent care consultation",
    description: "Fast access to a doctor for symptoms that need same-day attention.",
    startingPrice: 15000,
    consultationModes: ["voice", "video"],
    estimatedDuration: 15,
  },
  {
    id: "svc-mental-health-consult",
    categoryId: "cat-mental-health",
    name: "Mental health consultation",
    description: "A private conversation with a mental health provider.",
    startingPrice: 25000,
    consultationModes: ["chat", "voice", "video"],
    estimatedDuration: 30,
  },
  {
    id: "svc-derm-consult",
    categoryId: "cat-dermatology",
    name: "Dermatology consultation",
    description: "Show a doctor a skin, hair, or nail concern and get guidance.",
    startingPrice: 15000,
    consultationModes: ["chat", "video"],
    estimatedDuration: 15,
  },
  {
    id: "svc-sexual-health-consult",
    categoryId: "cat-sexual-health",
    name: "Sexual health consultation",
    description: "Confidential, judgment-free care for sexual health concerns.",
    startingPrice: 15000,
    consultationModes: ["chat", "voice", "video"],
    estimatedDuration: 15,
  },
  {
    id: "svc-refill-consult",
    categoryId: "cat-prescription",
    name: "Prescription refill review",
    description: "Quick review to renew a medication you already take.",
    startingPrice: 8000,
    consultationModes: ["chat", "voice"],
    estimatedDuration: 10,
  },
  {
    id: "svc-lab-referral",
    categoryId: "cat-lab",
    name: "Lab referral consultation",
    description: "Discuss symptoms and get a referral to a nearby partner lab.",
    startingPrice: 10000,
    consultationModes: ["chat", "voice", "video"],
    estimatedDuration: 15,
  },
  {
    id: "svc-womens-health-consult",
    categoryId: "cat-womens-health",
    name: "Women's health consultation",
    description: "Talk through menstrual, reproductive, or general women's health concerns.",
    startingPrice: 15000,
    consultationModes: ["chat", "voice", "video"],
    estimatedDuration: 20,
  },
  {
    id: "svc-pediatric-consult",
    categoryId: "cat-pediatrics",
    name: "Pediatric consultation",
    description: "A doctor experienced in child health reviews your child's symptoms.",
    startingPrice: 12000,
    consultationModes: ["chat", "voice", "video"],
    estimatedDuration: 15,
  },
  {
    id: "svc-chronic-followup",
    categoryId: "cat-chronic",
    name: "Chronic condition check-in",
    description: "Review how a diagnosed condition is being managed and adjust the plan.",
    startingPrice: 10000,
    consultationModes: ["chat", "voice", "video"],
    estimatedDuration: 15,
  },
];

export const providers: Provider[] = [
  {
    id: "prov-amani",
    name: "Dr. Amani Otieno",
    specialty: "General Practice",
    credentials: "MBChB, Tanzania Medical Board",
    rating: 4.8,
    reviewCount: 312,
    languages: ["en", "sw"],
    price: 10000,
    consultationModes: ["chat", "voice", "video"],
    nextAvailableAt: "Today, 2:40 PM",
    isAvailableNow: true,
    photoUrl: "/generated/doctor-amani-otieno.png",
    bio: "General practitioner with 9 years of experience in primary and urgent care.",
    quote: "Dr. Otieno listened carefully and explained everything clearly. Felt like a real visit, just faster.",
    timeSlots: ["2:40 PM", "3:00 PM", "3:15 PM", "3:30 PM", "4:00 PM"],
  },
  {
    id: "prov-rehema",
    name: "Dr. Rehema Kilonzo",
    specialty: "Mental Health",
    credentials: "MD Psychiatry",
    rating: 4.9,
    reviewCount: 201,
    languages: ["en", "sw"],
    price: 25000,
    consultationModes: ["chat", "voice", "video"],
    nextAvailableAt: "Today, 4:00 PM",
    isAvailableNow: true,
    photoUrl: "",
    bio: "Psychiatrist focused on anxiety, depression, and stress-related concerns.",
    quote: "Compassionate and easy to talk to. I felt safe sharing what was going on.",
    timeSlots: ["4:00 PM", "4:15 PM", "4:30 PM", "5:00 PM", "5:15 PM"],
  },
  {
    id: "prov-musa",
    name: "Dr. Musa Abdi",
    specialty: "Dermatology",
    credentials: "MBChB, Dermatology Fellowship",
    rating: 4.7,
    reviewCount: 158,
    languages: ["en"],
    price: 15000,
    consultationModes: ["chat", "video"],
    nextAvailableAt: "Tomorrow, 9:15 AM",
    isAvailableNow: false,
    photoUrl: "",
    bio: "Dermatologist seeing common skin, hair, and nail concerns virtually.",
    quote: "Diagnosed my skin issue in minutes and the prescription was ready the same day.",
    timeSlots: ["9:15 AM", "9:30 AM", "9:45 AM", "10:15 AM", "10:30 AM"],
  },
  {
    id: "prov-faith",
    name: "Dr. Faith Wanjiru",
    specialty: "General Practice",
    credentials: "MBChB",
    rating: 4.6,
    reviewCount: 97,
    languages: ["en", "sw"],
    price: 10000,
    consultationModes: ["chat", "voice", "video"],
    nextAvailableAt: "Today, 3:10 PM",
    isAvailableNow: false,
    photoUrl: "",
    bio: "General practitioner with a focus on same-day and urgent care.",
    quote: "Quick, thorough, and didn't rush me. Exactly what I needed for urgent care.",
    timeSlots: ["3:10 PM", "3:30 PM", "3:45 PM", "4:00 PM", "4:30 PM"],
  },
  {
    id: "prov-brian",
    name: "Dr. Brian Mwangi",
    specialty: "Sexual Health",
    credentials: "MBChB, Sexual Health Certification",
    rating: 4.8,
    reviewCount: 134,
    languages: ["en", "sw"],
    price: 15000,
    consultationModes: ["chat", "voice", "video"],
    nextAvailableAt: "Today, 5:30 PM",
    isAvailableNow: true,
    photoUrl: "",
    bio: "Confidential, non-judgmental sexual and reproductive health care.",
    quote: "Non-judgmental and professional. Made a sensitive topic easy to discuss.",
    timeSlots: ["5:30 PM", "5:45 PM", "6:00 PM", "6:15 PM", "6:45 PM"],
  },
  {
    id: "prov-njeri",
    name: "Dr. Njeri Kamau",
    specialty: "Women's Health",
    credentials: "MBChB, Obstetrics & Gynaecology",
    rating: 4.9,
    reviewCount: 176,
    languages: ["en", "sw"],
    price: 15000,
    consultationModes: ["chat", "voice", "video"],
    nextAvailableAt: "Tomorrow, 10:00 AM",
    isAvailableNow: false,
    photoUrl: "/generated/doctor-njeri-kamau.png",
    bio: "Obstetrician-gynaecologist covering reproductive and general women's health.",
    quote: "Very knowledgeable and reassuring throughout the whole consultation.",
    timeSlots: ["10:00 AM", "10:15 AM", "10:30 AM", "10:45 AM", "11:15 AM"],
  },
  {
    id: "prov-samuel",
    name: "Dr. Samuel Otundo",
    specialty: "Pediatrics",
    credentials: "MBChB, Paediatrics Fellowship",
    rating: 4.8,
    reviewCount: 143,
    languages: ["en", "sw"],
    price: 12000,
    consultationModes: ["chat", "voice", "video"],
    nextAvailableAt: "Today, 6:15 PM",
    isAvailableNow: true,
    photoUrl: "",
    bio: "Pediatrician seeing common childhood illnesses and growth concerns virtually.",
    quote: "Great with my son, patient and clear about next steps for his care.",
    timeSlots: ["6:15 PM", "6:30 PM", "6:45 PM", "7:00 PM", "7:15 PM"],
  },
];

export const aiQualifications: AiQualification[] = [
  {
    id: "aiq-demo-1",
    patientReference: null,
    complaint: "I've had a sore throat and mild fever for two days.",
    questions: [
      "How many days have you had these symptoms?",
      "Do you have any difficulty breathing or swallowing?",
      "Any known allergies or current medications?",
    ],
    answers: [
      "About two days now.",
      "No difficulty breathing, just a sore throat.",
      "No known allergies, not on any medication.",
    ],
    patientConfirmedSummary:
      "Ninaumwa koo na nina homa kidogo kwa siku mbili. Sina shida ya kupumua au kumeza. Sina allergy ninazojua na situmii dawa kwa sasa.",
    urgencyLevel: "low",
    recommendedSpecialties: ["General Practice"],
    recommendedProviderIds: ["prov-amani", "prov-faith"],
    summaryForDoctor:
      "Patient reports 2 days of sore throat and mild fever, no breathing difficulty, no known allergies or current medications. No emergency red flags reported.",
  },
];

export const patientFiles: PatientFile[] = [
  {
    reference: "AF24-2026-01842",
    displayName: "Grace M.",
    age: 29,
    sex: "female",
    allergies: ["Penicillin"],
    conditions: [],
    medications: [],
    pastVisits: 2,
  },
];

export const intakes: Intake[] = [
  {
    reasonForVisit: "Sore throat and mild fever",
    symptoms: ["Sore throat", "Mild fever", "Fatigue"],
    duration: "2 days",
    severity: "mild",
    medications: [],
    attachments: [],
  },
];

export const checkouts: Checkout[] = [
  {
    id: "chk-demo-1",
    patientReference: "AF24-2026-01842",
    serviceId: "svc-general-consult",
    providerId: "prov-amani",
    consultationMode: "video",
    scheduledAt: "Today, 2:40 PM",
    subtotal: 10000,
    fees: 500,
    total: 10500,
    status: "paid",
  },
];

export const appointments: Appointment[] = [
  {
    id: "appt-demo-1",
    patientReference: "AF24-2026-01842",
    providerId: "prov-amani",
    serviceId: "svc-general-consult",
    scheduledAt: "Today, 2:40 PM",
    consultationMode: "video",
    status: "waiting",
    paymentStatus: "paid",
    intakeStatus: "complete",
    chatStatus: "not_started",
    voiceStatus: "not_started",
    videoStatus: "not_started",
  },
  {
    id: "appt-demo-2",
    patientReference: "AF24-2026-01918",
    providerId: "prov-rehema",
    serviceId: "svc-mental-health-consult",
    scheduledAt: "Today, 4:00 PM",
    consultationMode: "video",
    status: "scheduled",
    paymentStatus: "paid",
    intakeStatus: "complete",
    chatStatus: "not_started",
    voiceStatus: "not_started",
    videoStatus: "not_started",
  },
  {
    id: "appt-demo-3",
    patientReference: "AF24-2026-02004",
    providerId: "prov-musa",
    serviceId: "svc-derm-consult",
    scheduledAt: "Today, 11:15 AM",
    consultationMode: "chat",
    status: "in_progress",
    paymentStatus: "paid",
    intakeStatus: "complete",
    chatStatus: "active",
    voiceStatus: "not_started",
    videoStatus: "not_started",
  },
  {
    id: "appt-demo-4",
    patientReference: "AF24-2026-01760",
    providerId: "prov-faith",
    serviceId: "svc-urgent-consult",
    scheduledAt: "Today, 9:30 AM",
    consultationMode: "video",
    status: "completed",
    paymentStatus: "paid",
    intakeStatus: "complete",
    chatStatus: "not_started",
    voiceStatus: "not_started",
    videoStatus: "ended",
  },
  {
    id: "appt-demo-5",
    patientReference: "AF24-2026-02071",
    providerId: "prov-brian",
    serviceId: "svc-sexual-health-consult",
    scheduledAt: "Yesterday, 5:45 PM",
    consultationMode: "voice",
    status: "completed",
    paymentStatus: "paid",
    intakeStatus: "complete",
    chatStatus: "not_started",
    voiceStatus: "ended",
    videoStatus: "not_started",
  },
  {
    id: "appt-demo-6",
    patientReference: "AF24-2026-01655",
    providerId: "prov-njeri",
    serviceId: "svc-womens-health-consult",
    scheduledAt: "Tomorrow, 10:00 AM",
    consultationMode: "video",
    status: "scheduled",
    paymentStatus: "pending",
    intakeStatus: "in_progress",
    chatStatus: "not_started",
    voiceStatus: "not_started",
    videoStatus: "not_started",
  },
  {
    id: "appt-demo-7",
    patientReference: "AF24-2026-02118",
    providerId: "prov-samuel",
    serviceId: "svc-pediatric-consult",
    scheduledAt: "Today, 6:15 PM",
    consultationMode: "video",
    status: "scheduled",
    paymentStatus: "failed",
    intakeStatus: "not_started",
    chatStatus: "not_started",
    voiceStatus: "not_started",
    videoStatus: "not_started",
  },
  {
    id: "appt-demo-8",
    patientReference: "AF24-2026-01502",
    providerId: "prov-amani",
    serviceId: "svc-followup",
    scheduledAt: "Yesterday, 3:20 PM",
    consultationMode: "chat",
    status: "cancelled",
    paymentStatus: "failed",
    intakeStatus: "not_started",
    chatStatus: "not_started",
    voiceStatus: "not_started",
    videoStatus: "not_started",
  },
];

export const adminProviderMeta: AdminProviderMeta[] = [
  {
    providerId: "prov-amani",
    status: "active",
    licenseNumber: "KMB-11423",
    appointmentsThisWeek: 18,
    joinedAt: "Mar 2025",
  },
  {
    providerId: "prov-rehema",
    status: "active",
    licenseNumber: "KMB-20987",
    appointmentsThisWeek: 11,
    joinedAt: "Jun 2025",
  },
  {
    providerId: "prov-musa",
    status: "active",
    licenseNumber: "KMB-15602",
    appointmentsThisWeek: 9,
    joinedAt: "Feb 2025",
  },
  {
    providerId: "prov-faith",
    status: "suspended",
    licenseNumber: "KMB-18844",
    appointmentsThisWeek: 0,
    joinedAt: "Sep 2025",
  },
  {
    providerId: "prov-brian",
    status: "active",
    licenseNumber: "KMB-13390",
    appointmentsThisWeek: 7,
    joinedAt: "Jan 2025",
  },
  {
    providerId: "prov-njeri",
    status: "active",
    licenseNumber: "KMB-19255",
    appointmentsThisWeek: 14,
    joinedAt: "Apr 2025",
  },
  {
    providerId: "prov-samuel",
    status: "pending",
    licenseNumber: "KMB-21106",
    appointmentsThisWeek: 2,
    joinedAt: "Aug 2026",
  },
];

export const payments: Payment[] = [
  {
    id: "pay-demo-1",
    appointmentId: "appt-demo-1",
    patientReference: "AF24-2026-01842",
    providerId: "prov-amani",
    amount: 10500,
    currency: "TZS",
    method: "mpesa",
    status: "paid",
    confirmedByAdmin: true,
    createdAt: "Today, 2:38 PM",
  },
  {
    id: "pay-demo-2",
    appointmentId: "appt-demo-2",
    patientReference: "AF24-2026-01918",
    providerId: "prov-rehema",
    amount: 25500,
    currency: "TZS",
    method: "card",
    status: "paid",
    confirmedByAdmin: true,
    createdAt: "Today, 1:05 PM",
  },
  {
    id: "pay-demo-3",
    appointmentId: "appt-demo-3",
    patientReference: "AF24-2026-02004",
    providerId: "prov-musa",
    amount: 15500,
    currency: "TZS",
    method: "mpesa",
    status: "paid",
    confirmedByAdmin: true,
    createdAt: "Today, 11:10 AM",
  },
  {
    id: "pay-demo-4",
    appointmentId: "appt-demo-4",
    patientReference: "AF24-2026-01760",
    providerId: "prov-faith",
    amount: 15500,
    currency: "TZS",
    method: "cash",
    status: "paid",
    confirmedByAdmin: true,
    createdAt: "Today, 9:26 AM",
  },
  {
    id: "pay-demo-5",
    appointmentId: "appt-demo-5",
    patientReference: "AF24-2026-02071",
    providerId: "prov-brian",
    amount: 15500,
    currency: "TZS",
    method: "mpesa",
    status: "paid",
    confirmedByAdmin: true,
    createdAt: "Yesterday, 5:42 PM",
  },
  {
    id: "pay-demo-6",
    appointmentId: "appt-demo-6",
    patientReference: "AF24-2026-01655",
    providerId: "prov-njeri",
    amount: 15500,
    currency: "TZS",
    method: "mpesa",
    status: "pending",
    confirmedByAdmin: false,
    createdAt: "Today, 8:02 AM",
  },
  {
    id: "pay-demo-7",
    appointmentId: "appt-demo-7",
    patientReference: "AF24-2026-02118",
    providerId: "prov-samuel",
    amount: 12500,
    currency: "TZS",
    method: "card",
    status: "failed",
    confirmedByAdmin: false,
    createdAt: "Today, 5:58 PM",
  },
  {
    id: "pay-demo-8",
    appointmentId: "appt-demo-8",
    patientReference: "AF24-2026-01502",
    providerId: "prov-amani",
    amount: 7500,
    currency: "TZS",
    method: "mpesa",
    status: "failed",
    confirmedByAdmin: false,
    createdAt: "Yesterday, 3:18 PM",
  },
];

export const auditLogs: AuditLogEntry[] = [
  {
    id: "audit-1",
    actorName: "Wanjiku Muriithi",
    actorRole: "admin",
    action: "payment_confirmed",
    entityLabel: "Payment pay-demo-3 (Dr. Musa Abdi)",
    createdAt: "Today, 11:11 AM",
  },
  {
    id: "audit-2",
    actorName: "Dr. Amani Otieno",
    actorRole: "doctor",
    action: "prescription_signed",
    entityLabel: "Paracetamol 500mg for AF24-2026-01842",
    createdAt: "Today, 3:05 PM",
  },
  {
    id: "audit-3",
    actorName: "Wanjiku Muriithi",
    actorRole: "admin",
    action: "provider_status_changed",
    entityLabel: "Dr. Faith Wanjiru set to suspended",
    createdAt: "Today, 8:40 AM",
  },
  {
    id: "audit-4",
    actorName: "Dr. Brian Mwangi",
    actorRole: "doctor",
    action: "lab_order_approved",
    entityLabel: "Full blood count, Rapid strep test - Sinza Community Lab",
    createdAt: "Yesterday, 5:50 PM",
  },
  {
    id: "audit-5",
    actorName: "James Otieno",
    actorRole: "pharmacy_staff",
    action: "pharmacy_order_status_changed",
    entityLabel: "rx-order-demo-1 moved to preparing",
    createdAt: "Yesterday, 4:12 PM",
  },
  {
    id: "audit-6",
    actorName: "Wanjiku Muriithi",
    actorRole: "admin",
    action: "service_price_changed",
    entityLabel: "General consultation base price updated to TZS 10,000",
    createdAt: "2 days ago",
  },
  {
    id: "audit-7",
    actorName: "Wanjiku Muriithi",
    actorRole: "admin",
    action: "provider_added",
    entityLabel: "Dr. Samuel Otundo added, pending verification",
    createdAt: "3 days ago",
  },
  {
    id: "audit-8",
    actorName: "Wanjiku Muriithi",
    actorRole: "admin",
    action: "lab_location_updated",
    entityLabel: "Morogoro Road Diagnostics marked inactive",
    createdAt: "4 days ago",
  },
];

export const visitOutcomes: VisitOutcome[] = [
  {
    summary:
      "Patient presented with 2-day history of sore throat and mild fever, consistent with viral pharyngitis. No red flags identified. Advised rest, fluids, and over-the-counter pain relief.",
    prescription: [
      {
        medicationName: "Paracetamol",
        dosage: "500mg",
        instructions: "Take 1 tablet every 6 hours as needed for pain or fever",
        duration: "5 days",
      },
    ],
    labOrders: [],
    referrals: [],
    doctorSignature: "Dr. Amani Otieno",
    signedAt: "Today, 3:05 PM",
  },
];

export const labLocations: LabLocation[] = [
  {
    id: "lab-nairobi-central",
    name: "Dar Central Diagnostics",
    address: "Samora Avenue, Dar es Salaam",
    phone: "+255 712 123 456",
    region: "Dar es Salaam",
    latitude: -6.8161,
    longitude: 39.2803,
    openingHours: "Mon-Sat, 7:00 AM - 7:00 PM",
    mapUrl: "https://maps.google.com/?q=Dar+Central+Diagnostics",
    status: "active",
  },
  {
    id: "lab-westlands",
    name: "Sinza Community Lab",
    address: "Shekilango Road, Sinza",
    phone: "+255 713 654 321",
    region: "Dar es Salaam",
    latitude: -6.7794,
    longitude: 39.2247,
    openingHours: "Mon-Sun, 7:30 AM - 8:00 PM",
    mapUrl: "https://maps.google.com/?q=Sinza+Community+Lab",
    status: "active",
  },
  {
    id: "lab-kilimani",
    name: "Mikocheni Polyclinic Lab",
    address: "Mwai Kibaki Road, Mikocheni",
    phone: "+255 714 222 333",
    region: "Dar es Salaam",
    latitude: -6.7648,
    longitude: 39.2552,
    openingHours: "Mon-Sat, 7:00 AM - 8:00 PM",
    mapUrl: "https://maps.google.com/?q=Mikocheni+Polyclinic+Lab",
    status: "active",
  },
  {
    id: "lab-karen",
    name: "Masaki Diagnostic Centre",
    address: "Chole Road, Masaki",
    phone: "+255 715 444 555",
    region: "Dar es Salaam",
    latitude: -6.7542,
    longitude: 39.2759,
    openingHours: "Mon-Sat, 8:00 AM - 6:00 PM",
    mapUrl: "https://maps.google.com/?q=Masaki+Diagnostic+Centre",
    status: "active",
  },
  {
    id: "lab-eastleigh",
    name: "Kariakoo Community Lab",
    address: "Msimbazi Street, Kariakoo",
    phone: "+255 716 666 777",
    region: "Dar es Salaam",
    latitude: -6.8235,
    longitude: 39.2695,
    openingHours: "Mon-Sun, 7:00 AM - 9:00 PM",
    mapUrl: "https://maps.google.com/?q=Kariakoo+Community+Lab",
    status: "active",
  },
  {
    id: "lab-mombasa-road",
    name: "Morogoro Road Diagnostics",
    address: "Morogoro Road, Ubungo",
    phone: "+255 717 888 999",
    region: "Dar es Salaam",
    latitude: -6.7891,
    longitude: 39.2086,
    openingHours: "Mon-Sat, 8:00 AM - 6:00 PM",
    mapUrl: "https://maps.google.com/?q=Morogoro+Road+Diagnostics",
    status: "inactive",
  },
];

export const labOrders: LabOrder[] = [
  {
    id: "lab-order-demo-1",
    tests: ["Full blood count", "Rapid strep test"],
    status: "instructions_sent",
    labLocationId: "lab-westlands",
    mapUrl: "https://maps.google.com/?q=Sinza+Community+Lab",
    whatsappDeliveryStatus: "delivered",
    instructions: "No food or drink restrictions. Walk in any time during opening hours.",
  },
  {
    id: "lab-order-demo-2",
    tests: ["Malaria rapid test", "Widal test"],
    status: "results_pending",
    labLocationId: "lab-nairobi-central",
    mapUrl: "https://maps.google.com/?q=Dar+Central+Diagnostics",
    whatsappDeliveryStatus: "delivered",
    instructions: "Fasting not required. Bring your national ID for check-in.",
  },
  {
    id: "lab-order-demo-3",
    tests: ["HbA1c", "Lipid profile"],
    status: "ordered",
    labLocationId: "lab-kilimani",
    mapUrl: "https://maps.google.com/?q=Mikocheni+Polyclinic+Lab",
    whatsappDeliveryStatus: "not_sent",
    instructions: "8-hour fasting required before the blood draw.",
  },
  {
    id: "lab-order-demo-4",
    tests: ["Urinalysis"],
    status: "results_ready",
    labLocationId: "lab-karen",
    mapUrl: "https://maps.google.com/?q=Masaki+Diagnostic+Centre",
    whatsappDeliveryStatus: "delivered",
    instructions: "Collect a mid-stream sample in the provided container.",
  },
];

export const pharmacyItems: PharmacyItem[] = [
  {
    id: "rx-item-paracetamol",
    medicineName: "Paracetamol 500mg",
    category: "Pain relief",
    form: "Tablet",
    strength: "500mg",
    unitPrice: 150,
    stockStatus: "in_stock",
    requiresPrescription: false,
    photoUrl: "/generated/pharmacy-paracetamol.png",
  },
  {
    id: "rx-item-ibuprofen",
    medicineName: "Ibuprofen 400mg",
    category: "Pain relief",
    form: "Tablet",
    strength: "400mg",
    unitPrice: 180,
    stockStatus: "in_stock",
    requiresPrescription: false,
  },
  {
    id: "rx-item-amoxicillin",
    medicineName: "Amoxicillin 250mg",
    category: "Antibiotics",
    form: "Capsule",
    strength: "250mg",
    unitPrice: 320,
    stockStatus: "in_stock",
    requiresPrescription: true,
    photoUrl: "/generated/pharmacy-amoxicillin.png",
  },
  {
    id: "rx-item-cetirizine",
    medicineName: "Cetirizine 10mg",
    category: "Allergy",
    form: "Tablet",
    strength: "10mg",
    unitPrice: 210,
    stockStatus: "low_stock",
    requiresPrescription: false,
  },
  {
    id: "rx-item-loratadine",
    medicineName: "Loratadine 10mg",
    category: "Allergy",
    form: "Tablet",
    strength: "10mg",
    unitPrice: 240,
    stockStatus: "in_stock",
    requiresPrescription: false,
  },
  {
    id: "rx-item-vitamin-c",
    medicineName: "Vitamin C 1000mg",
    category: "Vitamins & supplements",
    form: "Effervescent tablet",
    strength: "1000mg",
    unitPrice: 450,
    stockStatus: "in_stock",
    requiresPrescription: false,
  },
  {
    id: "rx-item-multivitamin",
    medicineName: "Daily Multivitamin",
    category: "Vitamins & supplements",
    description: "Everyday multivitamin support for adults.",
    form: "Tablet",
    strength: "Once daily",
    unitPrice: 890,
    stockStatus: "in_stock",
    requiresPrescription: false,
    photoUrl: "/generated/pharmacy-multivitamin.png",
  },
  {
    id: "rx-item-zinc-vitamin-c",
    medicineName: "Zinc + Vitamin C",
    category: "Supplements",
    description: "Immune support supplement for adults.",
    form: "Tablet",
    strength: "Zinc 15mg + Vitamin C 500mg",
    unitPrice: 520,
    stockStatus: "in_stock",
    requiresPrescription: false,
  },
  {
    id: "rx-item-omega-3",
    medicineName: "Omega-3 Softgels",
    category: "Supplements",
    description: "Daily omega-3 supplement for heart and general wellness support.",
    form: "Softgel",
    strength: "1000mg",
    unitPrice: 1250,
    stockStatus: "in_stock",
    requiresPrescription: false,
  },
  {
    id: "rx-item-ors",
    medicineName: "Oral Rehydration Salts",
    category: "First aid",
    form: "Sachet",
    strength: "20.5g",
    unitPrice: 60,
    stockStatus: "in_stock",
    requiresPrescription: false,
    photoUrl: "/generated/pharmacy-ors.png",
  },
  {
    id: "rx-item-digital-thermometer",
    medicineName: "Digital Thermometer",
    category: "Medical devices",
    description: "Fast digital temperature reading for home and clinic use.",
    form: "Device",
    strength: "Oral/underarm",
    unitPrice: 650,
    stockStatus: "in_stock",
    requiresPrescription: false,
  },
  {
    id: "rx-item-bp-monitor",
    medicineName: "Digital BP Monitor",
    category: "Medical devices",
    description: "Upper-arm blood pressure monitor for home tracking.",
    form: "Device",
    strength: "Adult cuff",
    unitPrice: 3850,
    stockStatus: "low_stock",
    requiresPrescription: false,
  },
  {
    id: "rx-item-stethoscope",
    medicineName: "Clinical Stethoscope",
    category: "Hospital tools",
    description: "Basic clinical stethoscope for healthcare staff and home caregivers.",
    form: "Tool",
    strength: "Dual head",
    unitPrice: 1450,
    stockStatus: "in_stock",
    requiresPrescription: false,
  },
  {
    id: "rx-item-exam-gloves",
    medicineName: "Examination Gloves",
    category: "Hospital tools",
    description: "Disposable nitrile gloves for hygiene and basic care tasks.",
    form: "Box",
    strength: "100 pieces",
    unitPrice: 980,
    stockStatus: "in_stock",
    requiresPrescription: false,
  },
  {
    id: "rx-item-sterile-gauze",
    medicineName: "Sterile Gauze Pads",
    category: "Wound care",
    description: "Sterile gauze pads for dressing minor wounds.",
    form: "Pack",
    strength: "10 pads",
    unitPrice: 180,
    stockStatus: "in_stock",
    requiresPrescription: false,
  },
  {
    id: "rx-item-wound-dressing",
    medicineName: "Adhesive Wound Dressing",
    category: "Wound care",
    description: "Breathable adhesive dressing for cuts and post-care protection.",
    form: "Pack",
    strength: "5 dressings",
    unitPrice: 240,
    stockStatus: "in_stock",
    requiresPrescription: false,
  },
  {
    id: "rx-item-antiseptic",
    medicineName: "Antiseptic Wound Spray",
    category: "First aid",
    form: "Spray",
    strength: "100ml",
    unitPrice: 320,
    stockStatus: "low_stock",
    requiresPrescription: false,
    photoUrl: "/generated/pharmacy-antiseptic.png",
  },
  {
    id: "rx-item-cough-syrup",
    medicineName: "Cough Relief Syrup",
    category: "Cold & flu",
    form: "Syrup",
    strength: "100ml",
    unitPrice: 380,
    stockStatus: "in_stock",
    requiresPrescription: false,
  },
  {
    id: "rx-item-metformin",
    medicineName: "Metformin 500mg",
    category: "Chronic condition",
    form: "Tablet",
    strength: "500mg",
    unitPrice: 260,
    stockStatus: "in_stock",
    requiresPrescription: true,
  },
  {
    id: "rx-item-amlodipine",
    medicineName: "Amlodipine 5mg",
    category: "Chronic condition",
    form: "Tablet",
    strength: "5mg",
    unitPrice: 290,
    stockStatus: "out_of_stock",
    requiresPrescription: true,
  },
];

export const pharmacyOrders: PharmacyOrder[] = [
  {
    id: "rx-order-demo-1",
    patientReference: "AF24-2026-01842",
    prescriptionId: "presc-demo-1",
    items: [
      {
        pharmacyItemId: "rx-item-paracetamol",
        prescribedMedicationName: "Paracetamol 500mg",
        quantity: 20,
        availabilityStatus: "in_stock",
        substitutionRequested: false,
      },
    ],
    fulfillmentMethod: "pickup",
    subtotal: 150,
    fees: 0,
    total: 150,
    status: "preparing",
    substitutionRequested: false,
  },
  {
    id: "rx-order-demo-2",
    patientReference: "AF24-2026-01760",
    prescriptionId: "presc-demo-2",
    items: [
      {
        pharmacyItemId: "rx-item-amoxicillin",
        prescribedMedicationName: "Amoxicillin 250mg",
        quantity: 21,
        availabilityStatus: "in_stock",
        substitutionRequested: false,
      },
    ],
    fulfillmentMethod: "delivery",
    subtotal: 320,
    fees: 150,
    total: 470,
    status: "out_for_delivery",
    substitutionRequested: false,
  },
  {
    id: "rx-order-demo-3",
    patientReference: "AF24-2026-02071",
    prescriptionId: "presc-demo-3",
    items: [
      {
        pharmacyItemId: "rx-item-amlodipine",
        prescribedMedicationName: "Amlodipine 5mg",
        quantity: 30,
        availabilityStatus: "out_of_stock",
        substitutionRequested: true,
      },
    ],
    fulfillmentMethod: "pickup",
    subtotal: 290,
    fees: 0,
    total: 290,
    status: "pending",
    substitutionRequested: true,
  },
  {
    id: "rx-order-demo-4",
    patientReference: "AF24-2026-01918",
    prescriptionId: "presc-demo-4",
    items: [
      {
        pharmacyItemId: "rx-item-cetirizine",
        prescribedMedicationName: "Cetirizine 10mg",
        quantity: 10,
        availabilityStatus: "low_stock",
        substitutionRequested: false,
      },
    ],
    fulfillmentMethod: "pickup",
    subtotal: 210,
    fees: 0,
    total: 210,
    status: "completed",
    substitutionRequested: false,
  },
];

export function getServicesForCategory(categoryId: string): Service[] {
  return services.filter((service) => service.categoryId === categoryId);
}

export function getProviderById(providerId: string): Provider | undefined {
  return providers.find((provider) => provider.id === providerId);
}

export function getServiceById(serviceId: string): Service | undefined {
  return services.find((service) => service.id === serviceId);
}

export function getAverageProviderRating(): number {
  const total = providers.reduce((sum, provider) => sum + provider.rating, 0);
  return Math.round((total / providers.length) * 10) / 10;
}

export function getPharmacyItemById(itemId: string): PharmacyItem | undefined {
  return pharmacyItems.find((item) => item.id === itemId);
}

export function getAdminProviderMeta(providerId: string): AdminProviderMeta | undefined {
  return adminProviderMeta.find((meta) => meta.providerId === providerId);
}

export function getLabLocationById(labLocationId: string): LabLocation | undefined {
  return labLocations.find((location) => location.id === labLocationId);
}
