// Realistic mock data for the Afya24 clickable prototype.
// Nothing here is a real API call — components should be structured so a
// future TanStack Query hook can replace these exports without changing shape.
//
// Most of what used to live here (providers, appointments detail, payments,
// checkouts, visit outcomes, patient files, AI qualification demo data, lab
// locations) has been replaced by real Supabase-backed data throughout the
// app and was deleted from this file as dead code. What's left below is
// still actually imported: service categories/services (home page + admin
// services tab) and the admin dashboard's appointments/audit-log/lab-orders
// tabs, none of which have a real data source built yet.

import type { Appointment, AuditLogEntry, LabOrder, Service, ServiceCategory } from "./types";

export const serviceCategories: ServiceCategory[] = [
  {
    id: "cat-general",
    name: "General doctor",
    description: "Talk to a general practitioner about any everyday health concern.",
    icon: "stethoscope",
    popularServices: ["svc-general-consult", "svc-followup"],
  },
  {
    id: "cat-urgent",
    name: "Urgent care",
    description: "Same-day care for issues that need attention soon but aren't emergencies.",
    icon: "alarm-clock",
    popularServices: ["svc-urgent-consult"],
  },
  {
    id: "cat-mental-health",
    name: "Mental health",
    description: "Support for anxiety, depression, stress, and sleep issues.",
    icon: "brain",
    popularServices: ["svc-mental-health-consult"],
  },
  {
    id: "cat-dermatology",
    name: "Dermatology",
    description: "Skin, hair, and nail concerns reviewed by a doctor.",
    icon: "scan-face",
    popularServices: ["svc-derm-consult"],
  },
  {
    id: "cat-sexual-health",
    name: "Sexual health",
    description: "Confidential care for sexual and reproductive health concerns.",
    icon: "heart-pulse",
    popularServices: ["svc-sexual-health-consult"],
  },
  {
    id: "cat-prescription",
    name: "Prescription refill",
    description: "Renew an existing prescription without an in-person visit.",
    icon: "pill",
    popularServices: ["svc-refill-consult"],
  },
  {
    id: "cat-lab",
    name: "Lab tests",
    description: "Get a doctor's referral for lab tests at a nearby partner lab.",
    icon: "flask-conical",
    popularServices: ["svc-lab-referral"],
  },
  {
    id: "cat-womens-health",
    name: "Women's health",
    description: "Care for menstrual, reproductive, and general women's health concerns.",
    icon: "heart-pulse",
    popularServices: ["svc-womens-health-consult"],
  },
  {
    id: "cat-pediatrics",
    name: "Pediatrics",
    description: "Care for your child from a doctor experienced in pediatric health.",
    icon: "baby",
    popularServices: ["svc-pediatric-consult"],
  },
  {
    id: "cat-chronic",
    name: "Chronic condition follow-up",
    description: "Ongoing check-ins for diabetes, hypertension, asthma, and similar conditions.",
    icon: "repeat",
    popularServices: ["svc-chronic-followup"],
  },
];

export const services: Service[] = [
  {
    id: "svc-general-consult",
    categoryId: "cat-general",
    name: "General consultation",
    description: "A general check-in for any health concern with a licensed doctor.",
    startingPrice: 10000,
    consultationModes: ["chat", "voice", "video"],
    estimatedDuration: 15,
  },
  {
    id: "svc-followup",
    categoryId: "cat-general",
    name: "Follow-up visit",
    description: "A shorter visit to review progress after a previous consultation.",
    startingPrice: 7000,
    consultationModes: ["chat", "voice", "video"],
    estimatedDuration: 10,
  },
  {
    id: "svc-urgent-consult",
    categoryId: "cat-urgent",
    name: "Urgent care consultation",
    description: "Fast access to a doctor for symptoms that need same-day attention.",
    startingPrice: 15000,
    consultationModes: ["voice", "video"],
    estimatedDuration: 15,
  },
  {
    id: "svc-mental-health-consult",
    categoryId: "cat-mental-health",
    name: "Mental health consultation",
    description: "A private conversation with a mental health provider.",
    startingPrice: 25000,
    consultationModes: ["chat", "voice", "video"],
    estimatedDuration: 30,
  },
  {
    id: "svc-derm-consult",
    categoryId: "cat-dermatology",
    name: "Dermatology consultation",
    description: "Show a doctor a skin, hair, or nail concern and get guidance.",
    startingPrice: 15000,
    consultationModes: ["chat", "video"],
    estimatedDuration: 15,
  },
  {
    id: "svc-sexual-health-consult",
    categoryId: "cat-sexual-health",
    name: "Sexual health consultation",
    description: "Confidential, judgment-free care for sexual health concerns.",
    startingPrice: 15000,
    consultationModes: ["chat", "voice", "video"],
    estimatedDuration: 15,
  },
  {
    id: "svc-refill-consult",
    categoryId: "cat-prescription",
    name: "Prescription refill review",
    description: "Quick review to renew a medication you already take.",
    startingPrice: 8000,
    consultationModes: ["chat", "voice"],
    estimatedDuration: 10,
  },
  {
    id: "svc-lab-referral",
    categoryId: "cat-lab",
    name: "Lab referral consultation",
    description: "Discuss symptoms and get a referral to a nearby partner lab.",
    startingPrice: 10000,
    consultationModes: ["chat", "voice", "video"],
    estimatedDuration: 15,
  },
  {
    id: "svc-womens-health-consult",
    categoryId: "cat-womens-health",
    name: "Women's health consultation",
    description: "Talk through menstrual, reproductive, or general women's health concerns.",
    startingPrice: 15000,
    consultationModes: ["chat", "voice", "video"],
    estimatedDuration: 20,
  },
  {
    id: "svc-pediatric-consult",
    categoryId: "cat-pediatrics",
    name: "Pediatric consultation",
    description: "A doctor experienced in child health reviews your child's symptoms.",
    startingPrice: 12000,
    consultationModes: ["chat", "voice", "video"],
    estimatedDuration: 15,
  },
  {
    id: "svc-chronic-followup",
    categoryId: "cat-chronic",
    name: "Chronic condition check-in",
    description: "Review how a diagnosed condition is being managed and adjust the plan.",
    startingPrice: 10000,
    consultationModes: ["chat", "voice", "video"],
    estimatedDuration: 15,
  },
];

export const appointments: Appointment[] = [
  {
    id: "appt-demo-1",
    patientReference: "AF24-2026-01842",
    providerId: "prov-amani",
    serviceId: "svc-general-consult",
    scheduledAt: "Today, 2:40 PM",
    consultationMode: "video",
    status: "waiting",
    paymentStatus: "paid",
    intakeStatus: "complete",
    chatStatus: "not_started",
    voiceStatus: "not_started",
    videoStatus: "not_started",
  },
  {
    id: "appt-demo-2",
    patientReference: "AF24-2026-01918",
    providerId: "prov-rehema",
    serviceId: "svc-mental-health-consult",
    scheduledAt: "Today, 4:00 PM",
    consultationMode: "video",
    status: "scheduled",
    paymentStatus: "paid",
    intakeStatus: "complete",
    chatStatus: "not_started",
    voiceStatus: "not_started",
    videoStatus: "not_started",
  },
  {
    id: "appt-demo-3",
    patientReference: "AF24-2026-02004",
    providerId: "prov-musa",
    serviceId: "svc-derm-consult",
    scheduledAt: "Today, 11:15 AM",
    consultationMode: "chat",
    status: "in_progress",
    paymentStatus: "paid",
    intakeStatus: "complete",
    chatStatus: "active",
    voiceStatus: "not_started",
    videoStatus: "not_started",
  },
  {
    id: "appt-demo-4",
    patientReference: "AF24-2026-01760",
    providerId: "prov-faith",
    serviceId: "svc-urgent-consult",
    scheduledAt: "Today, 9:30 AM",
    consultationMode: "video",
    status: "completed",
    paymentStatus: "paid",
    intakeStatus: "complete",
    chatStatus: "not_started",
    voiceStatus: "not_started",
    videoStatus: "ended",
  },
  {
    id: "appt-demo-5",
    patientReference: "AF24-2026-02071",
    providerId: "prov-brian",
    serviceId: "svc-sexual-health-consult",
    scheduledAt: "Yesterday, 5:45 PM",
    consultationMode: "voice",
    status: "completed",
    paymentStatus: "paid",
    intakeStatus: "complete",
    chatStatus: "not_started",
    voiceStatus: "ended",
    videoStatus: "not_started",
  },
  {
    id: "appt-demo-6",
    patientReference: "AF24-2026-01655",
    providerId: "prov-njeri",
    serviceId: "svc-womens-health-consult",
    scheduledAt: "Tomorrow, 10:00 AM",
    consultationMode: "video",
    status: "scheduled",
    paymentStatus: "pending",
    intakeStatus: "in_progress",
    chatStatus: "not_started",
    voiceStatus: "not_started",
    videoStatus: "not_started",
  },
  {
    id: "appt-demo-7",
    patientReference: "AF24-2026-02118",
    providerId: "prov-samuel",
    serviceId: "svc-pediatric-consult",
    scheduledAt: "Today, 6:15 PM",
    consultationMode: "video",
    status: "scheduled",
    paymentStatus: "failed",
    intakeStatus: "not_started",
    chatStatus: "not_started",
    voiceStatus: "not_started",
    videoStatus: "not_started",
  },
  {
    id: "appt-demo-8",
    patientReference: "AF24-2026-01502",
    providerId: "prov-amani",
    serviceId: "svc-followup",
    scheduledAt: "Yesterday, 3:20 PM",
    consultationMode: "chat",
    status: "cancelled",
    paymentStatus: "failed",
    intakeStatus: "not_started",
    chatStatus: "not_started",
    voiceStatus: "not_started",
    videoStatus: "not_started",
  },
];

export const auditLogs: AuditLogEntry[] = [
  {
    id: "audit-1",
    actorName: "Wanjiku Muriithi",
    actorRole: "admin",
    action: "payment_confirmed",
    entityLabel: "Payment pay-demo-3 (Dr. Musa Abdi)",
    createdAt: "Today, 11:11 AM",
  },
  {
    id: "audit-2",
    actorName: "Dr. Amani Otieno",
    actorRole: "doctor",
    action: "prescription_signed",
    entityLabel: "Paracetamol 500mg for AF24-2026-01842",
    createdAt: "Today, 3:05 PM",
  },
  {
    id: "audit-3",
    actorName: "Wanjiku Muriithi",
    actorRole: "admin",
    action: "provider_status_changed",
    entityLabel: "Dr. Faith Wanjiru set to suspended",
    createdAt: "Today, 8:40 AM",
  },
  {
    id: "audit-4",
    actorName: "Dr. Brian Mwangi",
    actorRole: "doctor",
    action: "lab_order_approved",
    entityLabel: "Full blood count, Rapid strep test - Sinza Community Lab",
    createdAt: "Yesterday, 5:50 PM",
  },
  {
    id: "audit-5",
    actorName: "James Otieno",
    actorRole: "pharmacy_staff",
    action: "pharmacy_order_status_changed",
    entityLabel: "rx-order-demo-1 moved to preparing",
    createdAt: "Yesterday, 4:12 PM",
  },
  {
    id: "audit-6",
    actorName: "Wanjiku Muriithi",
    actorRole: "admin",
    action: "service_price_changed",
    entityLabel: "General consultation base price updated to TZS 10,000",
    createdAt: "2 days ago",
  },
  {
    id: "audit-7",
    actorName: "Wanjiku Muriithi",
    actorRole: "admin",
    action: "provider_added",
    entityLabel: "Dr. Samuel Otundo added, pending verification",
    createdAt: "3 days ago",
  },
  {
    id: "audit-8",
    actorName: "Wanjiku Muriithi",
    actorRole: "admin",
    action: "lab_location_updated",
    entityLabel: "Morogoro Road Diagnostics marked inactive",
    createdAt: "4 days ago",
  },
];

export const labOrders: LabOrder[] = [
  {
    id: "lab-order-demo-1",
    tests: ["Full blood count", "Rapid strep test"],
    status: "instructions_sent",
    labLocationId: "lab-westlands",
    mapUrl: "https://maps.google.com/?q=Sinza+Community+Lab",
    whatsappDeliveryStatus: "delivered",
    instructions: "No food or drink restrictions. Walk in any time during opening hours.",
  },
  {
    id: "lab-order-demo-2",
    tests: ["Malaria rapid test", "Widal test"],
    status: "results_pending",
    labLocationId: "lab-nairobi-central",
    mapUrl: "https://maps.google.com/?q=Dar+Central+Diagnostics",
    whatsappDeliveryStatus: "delivered",
    instructions: "Fasting not required. Bring your national ID for check-in.",
  },
  {
    id: "lab-order-demo-3",
    tests: ["HbA1c", "Lipid profile"],
    status: "ordered",
    labLocationId: "lab-kilimani",
    mapUrl: "https://maps.google.com/?q=Mikocheni+Polyclinic+Lab",
    whatsappDeliveryStatus: "not_sent",
    instructions: "8-hour fasting required before the blood draw.",
  },
  {
    id: "lab-order-demo-4",
    tests: ["Urinalysis"],
    status: "results_ready",
    labLocationId: "lab-karen",
    mapUrl: "https://maps.google.com/?q=Masaki+Diagnostic+Centre",
    whatsappDeliveryStatus: "delivered",
    instructions: "Collect a mid-stream sample in the provided container.",
  },
];
